version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  web:
    build: .
    container_name: django_container
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app


volumes:
  postgres_data:

networks:
  app:

